### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by FedorBuggins** [FedorBuggins/hmd#5]
- [ ] Notifications via Telegram Bot
- [ ] Scope option
- [ ] Verbose option
- [ ] Pretty logs
- [ ] Publish crate
- [ ] Completions
- [ ] Man
- [ ] Update README
- [x] Status option for deploy
- [x] Log option for deploy
- [ ] Config path option
